# Generated by Django 2.2.4 on 2021-06-02 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thought',
            old_name='owner',
            new_name='poster',
        ),
    ]
